# Generated by Django 3.2.15 on 2022-09-02 13:15

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220831_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipetag',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipetag',
            name='tag',
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ['user'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='unique subs',
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='запрет подписки на самого себя',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='following',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='follower',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.BigIntegerField(verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/recipe/', verbose_name='Изображение рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique subs'),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('author')), _negated=True), name='запрет подписки на самого себя'),
        ),
        migrations.DeleteModel(
            name='RecipeTag',
        ),
    ]
